# Generated by Django 3.1.2 on 2020-10-29 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish_date')),
                ('description', models.TextField()),
                ('summary', models.CharField(max_length=300)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('main_photo', models.ImageField(upload_to='blog/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d/')),
            ],
            options={
                'ordering': ('-publish_date',),
            },
        ),
    ]
