# Generated by Django 3.1.2 on 2020-11-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201111_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='main_photo',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_6',
        ),
    ]
